{% set name = "pycares" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0154fc5753b088758fbec9bc137e1b24bb84fc0c6a09725c8bac25a342311cd

build:
  number: 4
  skip: true  # [py<=35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cffi >=1.5.0
  run:
    - python
    - cffi >=1.5.0

test:
  imports:
    - pycares
  commands:
    - python -m pycares google.com

about:
  home: https://pypi.org/project/pycares/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for c-ares
  description: |
    pycares is a Python module which provides an interface to c-ares. c-ares
    is a C library that performs DNS requests and name resolutions
    asynchronously.
  doc_url: http://readthedocs.org/docs/pycares/
  dev_url: https://github.com/saghul/pycares

extra:
  recipe-maintainers:
    - CurtLH
