{% set name = "pycares" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9df70dce6e05afa5d477f48959170e569485e20dad1a089c4cf3b2d7ffbd8bf9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cffi >=1.5.0
    - setuptools
  run:
    - python
    - cffi >=1.5.0

test:
  requires:
    - pip
  imports:
    - pycares
  commands:
    - python -m pycares google.com
    - pip check

about:
  home: https://pypi.org/project/pycares/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for c-ares
  description: |
    pycares is a Python module which provides an interface to c-ares. c-ares
    is a C library that performs DNS requests and name resolutions
    asynchronously.
  doc_url: http://readthedocs.org/docs/pycares/
  dev_url: https://github.com/saghul/pycares

extra:
  recipe-maintainers:
    - CurtLH
    - xhochy
