{% set name = "pycares" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da1899fde778f9b8736712283eccbf7b654248779b349d139cd28eb30b0fa8cd

build:
  number: 0
  skip: true  # [py<=35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cffi >=1.5.0
  run:
    - python
    - cffi >=1.5.0

test:
  imports:
    - pycares
  commands:
    - python -m pycares google.com

about:
  home: https://pypi.org/project/pycares/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for c-ares
  description: |
    pycares is a Python module which provides an interface to c-ares. c-ares
    is a C library that performs DNS requests and name resolutions
    asynchronously.
  doc_url: http://readthedocs.org/docs/pycares/
  dev_url: https://github.com/saghul/pycares

extra:
  recipe-maintainers:
    - CurtLH
