{% set name = "pycares" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 025b6c2ffea4e9fb8f9a097381c2fecb24aff23fbd6906e70da22ec9ba60e19d

build:
  number: 0
  skip: true  # [py<=35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cffi >=1.5.0
    - setuptools
  run:
    - python
    - cffi >=1.5.0

test:
  requires:
    - python
  imports:
    - pycares
  commands:
    - python -m pycares google.com
    - pip check

about:
  home: https://pypi.org/project/pycares/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface for c-ares
  description: |
    pycares is a Python module which provides an interface to c-ares. c-ares
    is a C library that performs DNS requests and name resolutions
    asynchronously.
  doc_url: http://readthedocs.org/docs/pycares/
  dev_url: https://github.com/saghul/pycares

extra:
  recipe-maintainers:
    - CurtLH
